#!/usr/bin/env bash
# Derives the generated iOS version xcconfig from the single source of truth,
# apps/v1_ios/version.properties. Config/Shared.xcconfig includes the generated
# file unconditionally, so a project generated without running this script fails
# loudly at build time instead of silently baking in a stale or wrong version.
#
# Mirrors the Android contract in apps/v1_android/app/build.gradle.kts:
# versionCode must be a positive integer and versionName must be MAJOR.MINOR.PATCH.
set -Eeuo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
properties="${repo_root}/apps/v1_ios/version.properties"
generated="${repo_root}/apps/v1_ios/Config/Version.generated.xcconfig"

if [[ ! -f "${properties}" ]]; then
  echo "Missing iOS version source of truth: ${properties}" >&2
  exit 1
fi

read_property() {
  # Reads key=value, ignoring comments, surrounding whitespace, and CR line endings.
  sed -n "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*\(.*\)[[:space:]]*$/\1/p" "${properties}" \
    | tr -d '\r' \
    | tail -n 1
}

version_code="$(read_property versionCode)"
version_name="$(read_property versionName)"

if [[ ! "${version_code}" =~ ^[0-9]+$ ]] || (( version_code <= 0 )); then
  echo "version.properties must contain a positive integer versionCode. Found: '${version_code}'" >&2
  exit 1
fi
if [[ ! "${version_name}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "version.properties versionName must use MAJOR.MINOR.PATCH. Found: '${version_name}'" >&2
  exit 1
fi

mkdir -p "$(dirname "${generated}")"
cat > "${generated}" <<EOF
// Generated by scripts/release/generate-ios-version-xcconfig.sh from
// apps/v1_ios/version.properties. Do not edit and do not commit.
MARKETING_VERSION = ${version_name}
CURRENT_PROJECT_VERSION = ${version_code}
EOF

echo "Wrote ${generated} (MARKETING_VERSION=${version_name}, CURRENT_PROJECT_VERSION=${version_code})"
