import type { TournamentDetailRow } from './tournaments-read.query';

export function presentTournamentDetail(row: TournamentDetailRow) {
  return {
    id: row.id,
    sportId: row.sportId,
    sport: { code: row.sport.code, name: row.sport.name },
    title: row.title,
    status: row.status,
    format: row.format,
    registrationDeadlineAt: row.registrationDeadlineAt?.toISOString() ?? null,
    rosterDeadlineAt: row.rosterDeadlineAt?.toISOString() ?? null,
    scheduledAt: row.scheduledAt?.toISOString() ?? null,
    scheduledEndAt: row.scheduledEndAt?.toISOString() ?? null,
    venue: row.venue,
    latitude: row.latitude,
    longitude: row.longitude,
    coverImageUrl: row.coverImageUrl,
    teamCount: row.teamCount,
    minPlayers: row.minPlayers,
    maxPlayers: row.maxPlayers,
    genderCategory: row.genderCategory,
    genderMinMale: row.genderMinMale,
    genderMaxMale: row.genderMaxMale,
    genderMinFemale: row.genderMinFemale,
    genderMaxFemale: row.genderMaxFemale,
    entryFee: row.entryFee,
    rulesText: row.rulesText,
    refundPolicyText: row.refundPolicyText,
    prizePool: row.prizePool,
    prizeSummary: row.prizeSummary,
    prizeBreakdown: row.prizeBreakdown,
    promoHomeEnabled: row.promoHomeEnabled,
    promoHomeTitle: row.promoHomeTitle,
    promoHomeSubtitle: row.promoHomeSubtitle,
    promoHomeImageUrl: row.promoHomeImageUrl,
    promoHomeBadgeText: row.promoHomeBadgeText,
    promoHomeDateText: row.promoHomeDateText,
    promoHomeTeamsText: row.promoHomeTeamsText,
    promoHomeLocationText: row.promoHomeLocationText,
    promoHomePrizeText: row.promoHomePrizeText,
    promoHomePriority: row.promoHomePriority,
    promoListEnabled: row.promoListEnabled,
    promoListTitle: row.promoListTitle,
    promoListSubtitle: row.promoListSubtitle,
    promoListImageUrl: row.promoListImageUrl,
    promoListBadgeText: row.promoListBadgeText,
    promoListDateText: row.promoListDateText,
    promoListTeamsText: row.promoListTeamsText,
    promoListLocationText: row.promoListLocationText,
    promoListPrizeText: row.promoListPrizeText,
    promoListPriority: row.promoListPriority,
    campaignSlug: row.campaign?.status === 'published' ? row.campaign.slug : null,
    confirmedCount: row._count.registrations,
    participantTeams: row.registrations
      .filter((registration) => ['confirmed', 'waitlisted'].includes(registration.status))
      .sort((a, b) => {
        const aRank = a.status === 'confirmed' ? 0 : 1;
        const bRank = b.status === 'confirmed' ? 0 : 1;
        return aRank - bRank;
      })
      .map((registration) => ({
        registrationId: registration.id,
        teamId: registration.team.id,
        teamName: registration.team.name,
        teamLogoUrl: registration.team.profile?.logoUrl ?? null,
        teamRegionName: registration.team.region?.name ?? null,
        status: registration.status,
        confirmedAt: registration.confirmedAt?.toISOString() ?? null,
      })),
    pendingPaymentCount: row.registrations.filter((registration) =>
      ['awaiting_payment', 'payment_checking', 'paid'].includes(registration.status),
    ).length,
    groups: row.groups.map((group) => ({
      id: group.id,
      name: group.name,
      phase: group.phase,
      sortOrder: group.sortOrder,
      advanceCount: group.advanceCount,
      groupTeams: group.groupTeams.map((groupTeam) => ({
        id: groupTeam.id,
        registrationId: groupTeam.registrationId,
        teamId: groupTeam.registration.team.id,
        teamName: groupTeam.registration.team.name,
        sortOrder: groupTeam.sortOrder,
      })),
      standings: group.standings.map((standing) => ({
        registrationId: standing.registrationId,
        teamId: standing.registration.team.id,
        teamName: standing.registration.team.name,
        position: standing.position,
        points: standing.points,
        wins: standing.wins,
        draws: standing.draws,
        losses: standing.losses,
        goalsFor: standing.goalsFor,
        goalsAgainst: standing.goalsAgainst,
        recalculatedAt: standing.recalculatedAt?.toISOString() ?? null,
      })),
    })),
    fixtures: row.fixtures.map((fixture) => ({
      id: fixture.id,
      groupId: fixture.groupId,
      round: fixture.round,
      fixtureNumber: fixture.fixtureNumber,
      legNumber: fixture.legNumber,
      scheduledAt: fixture.scheduledAt?.toISOString() ?? null,
      venue: fixture.venue,
      status: fixture.status,
      homeRegistrationId: fixture.homeRegistrationId,
      homeTeamName: fixture.homeRegistration?.team.name ?? 'TBD',
      awayRegistrationId: fixture.awayRegistrationId,
      awayTeamName: fixture.awayRegistration?.team.name ?? 'TBD',
      result: fixture.result
        ? {
            homeScore: fixture.result.homeScore,
            awayScore: fixture.result.awayScore,
            hasPenalty: fixture.result.hasPenalty,
            homePenaltyScore: fixture.result.homePenaltyScore,
            awayPenaltyScore: fixture.result.awayPenaltyScore,
            note: fixture.result.note,
            recordedAt: fixture.result.recordedAt.toISOString(),
            goals: fixture.result.goals.map((goal) => ({
              id: goal.id,
              team: goal.team,
              playerId: goal.playerId,
              playerName: goal.playerName,
              minute: goal.minute,
            })),
          }
        : null,
      videos: fixture.videos.map((video) => ({
        id: video.id,
        title: video.title,
        url: video.url,
      })),
    })),
    announcements: row.announcements.map((announcement) => {
      if (!announcement.publishedAt) {
        throw new TypeError('Public tournament announcement is missing publishedAt');
      }
      return {
        id: announcement.id,
        title: announcement.title,
        body: announcement.body,
        category: announcement.category,
        audience: announcement.audience,
        publishedAt: announcement.publishedAt.toISOString(),
        createdAt: announcement.createdAt.toISOString(),
      };
    }),
    sponsors: row.sponsors.map((sponsor) => ({
      id: sponsor.id,
      name: sponsor.name,
      description: sponsor.description,
      logoUrl: sponsor.logoUrl,
      websiteUrl: sponsor.websiteUrl,
      instagramUrl: sponsor.instagramUrl,
      benefitText: sponsor.benefitText,
      boothText: sponsor.boothText,
      eventTitle: sponsor.eventTitle,
      eventDescription: sponsor.eventDescription,
      eventResultText: sponsor.eventResultText,
      sortOrder: sponsor.sortOrder,
    })),
    createdAt: row.createdAt.toISOString(),
    updatedAt: row.updatedAt.toISOString(),
    reviews: (row.reviews ?? []).map((review) => ({
      id: review.id,
      authorId: review.authorUserId,
      authorNickname: review.author?.profile?.nickname ?? '익명',
      authorProfileImageUrl: review.author?.profile?.profileImageUrl ?? null,
      teamName: review.teamName ?? null,
      rating: review.rating,
      comment: review.comment ?? null,
      photoUrls: review.photoUrls,
      createdAt: review.createdAt.toISOString(),
    })),
    awards: (row.awards ?? []).map((award) => ({
      id: award.id,
      awardType: award.awardType,
      awardLabel: award.awardLabel,
      recipientName: award.recipientName,
      teamName: award.teamName ?? null,
      note: award.note ?? null,
    })),
  };
}
