WITH parent_rows(code, name, sort_order, center_lat, center_lng) AS (
  VALUES
    ('seoul', '서울', 1, 37.5665, 126.9780),
    ('busan', '부산', 2, 35.1796, 129.0756),
    ('daegu', '대구', 3, 35.8714, 128.6014),
    ('incheon', '인천', 4, 37.4563, 126.7052),
    ('gwangju', '광주', 5, 35.1595, 126.8526),
    ('daejeon', '대전', 6, 36.3504, 127.3845),
    ('ulsan', '울산', 7, 35.5384, 129.3114),
    ('sejong', '세종', 8, 36.4800, 127.2890),
    ('gyeonggi', '경기', 9, 37.4138, 127.5183),
    ('gangwon', '강원', 10, 37.8228, 128.1555),
    ('chungbuk', '충북', 11, 36.8000, 127.7000),
    ('chungnam', '충남', 12, 36.5184, 126.8000),
    ('jeonbuk', '전북', 13, 35.7167, 127.1442),
    ('jeonnam', '전남', 14, 34.8679, 126.9910),
    ('gyeongbuk', '경북', 15, 36.4919, 128.8889),
    ('gyeongnam', '경남', 16, 35.4606, 128.2132),
    ('jeju', '제주', 17, 33.4996, 126.5312)
)
INSERT INTO "v1_regions" ("id", "parent_id", "code", "name", "level", "center_lat", "center_lng", "is_active", "sort_order", "created_at", "updated_at")
SELECT 'region-' || code, NULL, code, name, 1, center_lat, center_lng, true, sort_order, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM parent_rows
ON CONFLICT ("code") DO UPDATE SET
  "parent_id" = NULL,
  "name" = EXCLUDED."name",
  "level" = 1,
  "center_lat" = EXCLUDED."center_lat",
  "center_lng" = EXCLUDED."center_lng",
  "is_active" = true,
  "sort_order" = EXCLUDED."sort_order",
  "updated_at" = CURRENT_TIMESTAMP;

WITH child_rows(parent_code, code, name, sort_order, center_lat, center_lng) AS (
  VALUES
    ('seoul', 'seoul-jongno', '종로구', 1, 37.5735, 126.9788),
    ('seoul', 'seoul-jung', '중구', 2, 37.5636, 126.9976),
    ('seoul', 'seoul-yongsan', '용산구', 3, 37.5326, 126.9905),
    ('seoul', 'seoul-seongdong', '성동구', 4, 37.5633, 127.0369),
    ('seoul', 'seoul-gwangjin', '광진구', 5, 37.5384, 127.0823),
    ('seoul', 'seoul-dongdaemun', '동대문구', 6, 37.5744, 127.0396),
    ('seoul', 'seoul-jungnang', '중랑구', 7, 37.6063, 127.0927),
    ('seoul', 'seoul-seongbuk', '성북구', 8, 37.5894, 127.0167),
    ('seoul', 'seoul-gangbuk', '강북구', 9, 37.6396, 127.0257),
    ('seoul', 'seoul-dobong', '도봉구', 10, 37.6688, 127.0471),
    ('seoul', 'seoul-nowon', '노원구', 11, 37.6542, 127.0568),
    ('seoul', 'seoul-eunpyeong', '은평구', 12, 37.6027, 126.9291),
    ('seoul', 'seoul-seodaemun', '서대문구', 13, 37.5791, 126.9368),
    ('seoul', 'seoul-mapo', '마포구', 14, 37.5663, 126.9019),
    ('seoul', 'seoul-yangcheon', '양천구', 15, 37.5169, 126.8664),
    ('seoul', 'seoul-gangseo', '강서구', 16, 37.5509, 126.8495),
    ('seoul', 'seoul-guro', '구로구', 17, 37.4955, 126.8877),
    ('seoul', 'seoul-geumcheon', '금천구', 18, 37.4569, 126.8958),
    ('seoul', 'seoul-yeongdeungpo', '영등포구', 19, 37.5264, 126.8962),
    ('seoul', 'seoul-dongjak', '동작구', 20, 37.5124, 126.9393),
    ('seoul', 'seoul-gwanak', '관악구', 21, 37.4784, 126.9516),
    ('seoul', 'seoul-seocho', '서초구', 22, 37.4836, 127.0327),
    ('seoul', 'seoul-gangnam', '강남구', 23, 37.5172, 127.0473),
    ('seoul', 'seoul-songpa', '송파구', 24, 37.5145, 127.1059),
    ('seoul', 'seoul-gangdong', '강동구', 25, 37.5301, 127.1238),
    ('gyeonggi', 'gyeonggi-suwon', '수원시', 1, 37.2636, 127.0286),
    ('gyeonggi', 'gyeonggi-seongnam', '성남시', 2, 37.4201, 127.1265),
    ('gyeonggi', 'gyeonggi-uijeongbu', '의정부시', 3, 37.7381, 127.0337),
    ('gyeonggi', 'gyeonggi-anyang', '안양시', 4, 37.3943, 126.9568),
    ('gyeonggi', 'gyeonggi-bucheon', '부천시', 5, 37.5035, 126.7660),
    ('gyeonggi', 'gyeonggi-gwangmyeong', '광명시', 6, 37.4786, 126.8646),
    ('gyeonggi', 'gyeonggi-pyeongtaek', '평택시', 7, 36.9921, 127.1127),
    ('gyeonggi', 'gyeonggi-dongducheon', '동두천시', 8, 37.9037, 127.0606),
    ('gyeonggi', 'gyeonggi-ansan', '안산시', 9, 37.3219, 126.8309),
    ('gyeonggi', 'gyeonggi-goyang', '고양시', 10, 37.6584, 126.8320),
    ('gyeonggi', 'gyeonggi-gwacheon', '과천시', 11, 37.4292, 126.9877),
    ('gyeonggi', 'gyeonggi-guri', '구리시', 12, 37.5943, 127.1296),
    ('gyeonggi', 'gyeonggi-namyangju', '남양주시', 13, 37.6360, 127.2165),
    ('gyeonggi', 'gyeonggi-osan', '오산시', 14, 37.1498, 127.0772),
    ('gyeonggi', 'gyeonggi-siheung', '시흥시', 15, 37.3800, 126.8029),
    ('gyeonggi', 'gyeonggi-gunpo', '군포시', 16, 37.3617, 126.9352),
    ('gyeonggi', 'gyeonggi-uiwang', '의왕시', 17, 37.3449, 126.9683),
    ('gyeonggi', 'gyeonggi-hanam', '하남시', 18, 37.5393, 127.2149),
    ('gyeonggi', 'gyeonggi-yongin', '용인시', 19, 37.2411, 127.1776),
    ('gyeonggi', 'gyeonggi-paju', '파주시', 20, 37.7599, 126.7799),
    ('gyeonggi', 'gyeonggi-icheon', '이천시', 21, 37.2723, 127.4350),
    ('gyeonggi', 'gyeonggi-anseong', '안성시', 22, 37.0080, 127.2797),
    ('gyeonggi', 'gyeonggi-gimpo', '김포시', 23, 37.6153, 126.7156),
    ('gyeonggi', 'gyeonggi-hwaseong', '화성시', 24, 37.1996, 126.8310),
    ('gyeonggi', 'gyeonggi-gwangju', '광주시', 25, 37.4294, 127.2550),
    ('gyeonggi', 'gyeonggi-yangju', '양주시', 26, 37.7853, 127.0458),
    ('gyeonggi', 'gyeonggi-pocheon', '포천시', 27, 37.8949, 127.2003),
    ('gyeonggi', 'gyeonggi-yeoju', '여주시', 28, 37.2983, 127.6371),
    ('gyeonggi', 'gyeonggi-yeoncheon', '연천군', 29, 38.0964, 127.0750),
    ('gyeonggi', 'gyeonggi-gapyeong', '가평군', 30, 37.8315, 127.5099),
    ('gyeonggi', 'gyeonggi-yangpyeong', '양평군', 31, 37.4917, 127.4876),
    ('busan', 'busan-jung', '중구', 1, NULL::double precision, NULL::double precision),
    ('busan', 'busan-seo', '서구', 2, NULL::double precision, NULL::double precision),
    ('busan', 'busan-dong', '동구', 3, NULL::double precision, NULL::double precision),
    ('busan', 'busan-yeongdo', '영도구', 4, NULL::double precision, NULL::double precision),
    ('busan', 'busan-busanjin', '부산진구', 5, NULL::double precision, NULL::double precision),
    ('busan', 'busan-dongnae', '동래구', 6, NULL::double precision, NULL::double precision),
    ('busan', 'busan-nam', '남구', 7, NULL::double precision, NULL::double precision),
    ('busan', 'busan-buk', '북구', 8, NULL::double precision, NULL::double precision),
    ('busan', 'busan-haeundae', '해운대구', 9, NULL::double precision, NULL::double precision),
    ('busan', 'busan-saha', '사하구', 10, NULL::double precision, NULL::double precision),
    ('busan', 'busan-geumjeong', '금정구', 11, NULL::double precision, NULL::double precision),
    ('busan', 'busan-gangseo', '강서구', 12, NULL::double precision, NULL::double precision),
    ('busan', 'busan-yeonje', '연제구', 13, NULL::double precision, NULL::double precision),
    ('busan', 'busan-suyeong', '수영구', 14, NULL::double precision, NULL::double precision),
    ('busan', 'busan-sasang', '사상구', 15, NULL::double precision, NULL::double precision),
    ('busan', 'busan-gijang', '기장군', 16, NULL::double precision, NULL::double precision),
    ('daegu', 'daegu-jung', '중구', 1, NULL::double precision, NULL::double precision),
    ('daegu', 'daegu-dong', '동구', 2, NULL::double precision, NULL::double precision),
    ('daegu', 'daegu-seo', '서구', 3, NULL::double precision, NULL::double precision),
    ('daegu', 'daegu-nam', '남구', 4, NULL::double precision, NULL::double precision),
    ('daegu', 'daegu-buk', '북구', 5, NULL::double precision, NULL::double precision),
    ('daegu', 'daegu-suseong', '수성구', 6, NULL::double precision, NULL::double precision),
    ('daegu', 'daegu-dalseo', '달서구', 7, NULL::double precision, NULL::double precision),
    ('daegu', 'daegu-dalseong', '달성군', 8, NULL::double precision, NULL::double precision),
    ('daegu', 'daegu-gunwi', '군위군', 9, NULL::double precision, NULL::double precision),
    ('incheon', 'incheon-jung', '중구', 1, NULL::double precision, NULL::double precision),
    ('incheon', 'incheon-dong', '동구', 2, NULL::double precision, NULL::double precision),
    ('incheon', 'incheon-michuhol', '미추홀구', 3, NULL::double precision, NULL::double precision),
    ('incheon', 'incheon-yeonsu', '연수구', 4, NULL::double precision, NULL::double precision),
    ('incheon', 'incheon-namdong', '남동구', 5, NULL::double precision, NULL::double precision),
    ('incheon', 'incheon-bupyeong', '부평구', 6, NULL::double precision, NULL::double precision),
    ('incheon', 'incheon-gyeyang', '계양구', 7, NULL::double precision, NULL::double precision),
    ('incheon', 'incheon-seo', '서구', 8, NULL::double precision, NULL::double precision),
    ('incheon', 'incheon-ganghwa', '강화군', 9, NULL::double precision, NULL::double precision),
    ('incheon', 'incheon-ongjin', '옹진군', 10, NULL::double precision, NULL::double precision),
    ('gwangju', 'gwangju-dong', '동구', 1, NULL::double precision, NULL::double precision),
    ('gwangju', 'gwangju-seo', '서구', 2, NULL::double precision, NULL::double precision),
    ('gwangju', 'gwangju-nam', '남구', 3, NULL::double precision, NULL::double precision),
    ('gwangju', 'gwangju-buk', '북구', 4, NULL::double precision, NULL::double precision),
    ('gwangju', 'gwangju-gwangsan', '광산구', 5, NULL::double precision, NULL::double precision),
    ('daejeon', 'daejeon-dong', '동구', 1, NULL::double precision, NULL::double precision),
    ('daejeon', 'daejeon-jung', '중구', 2, NULL::double precision, NULL::double precision),
    ('daejeon', 'daejeon-seo', '서구', 3, NULL::double precision, NULL::double precision),
    ('daejeon', 'daejeon-yuseong', '유성구', 4, NULL::double precision, NULL::double precision),
    ('daejeon', 'daejeon-daedeok', '대덕구', 5, NULL::double precision, NULL::double precision),
    ('ulsan', 'ulsan-jung', '중구', 1, NULL::double precision, NULL::double precision),
    ('ulsan', 'ulsan-nam', '남구', 2, NULL::double precision, NULL::double precision),
    ('ulsan', 'ulsan-dong', '동구', 3, NULL::double precision, NULL::double precision),
    ('ulsan', 'ulsan-buk', '북구', 4, NULL::double precision, NULL::double precision),
    ('ulsan', 'ulsan-ulju', '울주군', 5, NULL::double precision, NULL::double precision),
    ('sejong', 'sejong-city', '세종시', 1, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-chuncheon', '춘천시', 1, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-wonju', '원주시', 2, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-gangneung', '강릉시', 3, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-donghae', '동해시', 4, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-taebaek', '태백시', 5, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-sokcho', '속초시', 6, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-samcheok', '삼척시', 7, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-hongcheon', '홍천군', 8, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-hoengseong', '횡성군', 9, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-yeongwol', '영월군', 10, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-pyeongchang', '평창군', 11, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-jeongseon', '정선군', 12, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-cheorwon', '철원군', 13, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-hwacheon', '화천군', 14, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-yanggu', '양구군', 15, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-inje', '인제군', 16, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-goseong', '고성군', 17, NULL::double precision, NULL::double precision),
    ('gangwon', 'gangwon-yangyang', '양양군', 18, NULL::double precision, NULL::double precision),
    ('chungbuk', 'chungbuk-cheongju', '청주시', 1, NULL::double precision, NULL::double precision),
    ('chungbuk', 'chungbuk-chungju', '충주시', 2, NULL::double precision, NULL::double precision),
    ('chungbuk', 'chungbuk-jecheon', '제천시', 3, NULL::double precision, NULL::double precision),
    ('chungbuk', 'chungbuk-boeun', '보은군', 4, NULL::double precision, NULL::double precision),
    ('chungbuk', 'chungbuk-okcheon', '옥천군', 5, NULL::double precision, NULL::double precision),
    ('chungbuk', 'chungbuk-yeongdong', '영동군', 6, NULL::double precision, NULL::double precision),
    ('chungbuk', 'chungbuk-jeungpyeong', '증평군', 7, NULL::double precision, NULL::double precision),
    ('chungbuk', 'chungbuk-jincheon', '진천군', 8, NULL::double precision, NULL::double precision),
    ('chungbuk', 'chungbuk-goesan', '괴산군', 9, NULL::double precision, NULL::double precision),
    ('chungbuk', 'chungbuk-eumseong', '음성군', 10, NULL::double precision, NULL::double precision),
    ('chungbuk', 'chungbuk-danyang', '단양군', 11, NULL::double precision, NULL::double precision),
    ('chungnam', 'chungnam-cheonan', '천안시', 1, NULL::double precision, NULL::double precision),
    ('chungnam', 'chungnam-gongju', '공주시', 2, NULL::double precision, NULL::double precision),
    ('chungnam', 'chungnam-boryeong', '보령시', 3, NULL::double precision, NULL::double precision),
    ('chungnam', 'chungnam-asan', '아산시', 4, NULL::double precision, NULL::double precision),
    ('chungnam', 'chungnam-seosan', '서산시', 5, NULL::double precision, NULL::double precision),
    ('chungnam', 'chungnam-nonsan', '논산시', 6, NULL::double precision, NULL::double precision),
    ('chungnam', 'chungnam-gyeryong', '계룡시', 7, NULL::double precision, NULL::double precision),
    ('chungnam', 'chungnam-dangjin', '당진시', 8, NULL::double precision, NULL::double precision),
    ('chungnam', 'chungnam-geumsan', '금산군', 9, NULL::double precision, NULL::double precision),
    ('chungnam', 'chungnam-buyeo', '부여군', 10, NULL::double precision, NULL::double precision),
    ('chungnam', 'chungnam-seocheon', '서천군', 11, NULL::double precision, NULL::double precision),
    ('chungnam', 'chungnam-cheongyang', '청양군', 12, NULL::double precision, NULL::double precision),
    ('chungnam', 'chungnam-hongseong', '홍성군', 13, NULL::double precision, NULL::double precision),
    ('chungnam', 'chungnam-yesan', '예산군', 14, NULL::double precision, NULL::double precision),
    ('chungnam', 'chungnam-taean', '태안군', 15, NULL::double precision, NULL::double precision),
    ('jeonbuk', 'jeonbuk-jeonju', '전주시', 1, NULL::double precision, NULL::double precision),
    ('jeonbuk', 'jeonbuk-gunsan', '군산시', 2, NULL::double precision, NULL::double precision),
    ('jeonbuk', 'jeonbuk-iksan', '익산시', 3, NULL::double precision, NULL::double precision),
    ('jeonbuk', 'jeonbuk-jeongeup', '정읍시', 4, NULL::double precision, NULL::double precision),
    ('jeonbuk', 'jeonbuk-namwon', '남원시', 5, NULL::double precision, NULL::double precision),
    ('jeonbuk', 'jeonbuk-gimje', '김제시', 6, NULL::double precision, NULL::double precision),
    ('jeonbuk', 'jeonbuk-wanju', '완주군', 7, NULL::double precision, NULL::double precision),
    ('jeonbuk', 'jeonbuk-jinan', '진안군', 8, NULL::double precision, NULL::double precision),
    ('jeonbuk', 'jeonbuk-muju', '무주군', 9, NULL::double precision, NULL::double precision),
    ('jeonbuk', 'jeonbuk-jangsu', '장수군', 10, NULL::double precision, NULL::double precision),
    ('jeonbuk', 'jeonbuk-imsil', '임실군', 11, NULL::double precision, NULL::double precision),
    ('jeonbuk', 'jeonbuk-sunchang', '순창군', 12, NULL::double precision, NULL::double precision),
    ('jeonbuk', 'jeonbuk-gochang', '고창군', 13, NULL::double precision, NULL::double precision),
    ('jeonbuk', 'jeonbuk-buan', '부안군', 14, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-mokpo', '목포시', 1, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-yeosu', '여수시', 2, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-suncheon', '순천시', 3, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-naju', '나주시', 4, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-gwangyang', '광양시', 5, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-damyang', '담양군', 6, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-gokseong', '곡성군', 7, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-gurye', '구례군', 8, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-goheung', '고흥군', 9, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-boseong', '보성군', 10, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-hwasun', '화순군', 11, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-jangheung', '장흥군', 12, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-gangjin', '강진군', 13, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-haenam', '해남군', 14, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-yeongam', '영암군', 15, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-muan', '무안군', 16, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-hampyeong', '함평군', 17, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-yeonggwang', '영광군', 18, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-jangseong', '장성군', 19, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-wando', '완도군', 20, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-jindo', '진도군', 21, NULL::double precision, NULL::double precision),
    ('jeonnam', 'jeonnam-sinan', '신안군', 22, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-pohang', '포항시', 1, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-gyeongju', '경주시', 2, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-gimcheon', '김천시', 3, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-andong', '안동시', 4, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-gumi', '구미시', 5, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-yeongju', '영주시', 6, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-yeongcheon', '영천시', 7, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-sangju', '상주시', 8, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-mungyeong', '문경시', 9, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-gyeongsan', '경산시', 10, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-uiseong', '의성군', 11, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-cheongsong', '청송군', 12, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-yeongyang', '영양군', 13, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-yeongdeok', '영덕군', 14, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-cheongdo', '청도군', 15, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-goryeong', '고령군', 16, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-seongju', '성주군', 17, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-chilgok', '칠곡군', 18, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-yecheon', '예천군', 19, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-bonghwa', '봉화군', 20, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-uljin', '울진군', 21, NULL::double precision, NULL::double precision),
    ('gyeongbuk', 'gyeongbuk-ulleung', '울릉군', 22, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-changwon', '창원시', 1, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-jinju', '진주시', 2, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-tongyeong', '통영시', 3, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-sacheon', '사천시', 4, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-gimhae', '김해시', 5, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-miryang', '밀양시', 6, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-geoje', '거제시', 7, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-yangsan', '양산시', 8, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-uiryeong', '의령군', 9, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-haman', '함안군', 10, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-changnyeong', '창녕군', 11, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-goseong', '고성군', 12, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-namhae', '남해군', 13, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-hadong', '하동군', 14, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-sancheong', '산청군', 15, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-hamyang', '함양군', 16, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-geochang', '거창군', 17, NULL::double precision, NULL::double precision),
    ('gyeongnam', 'gyeongnam-hapcheon', '합천군', 18, NULL::double precision, NULL::double precision),
    ('jeju', 'jeju-jeju', '제주시', 1, NULL::double precision, NULL::double precision),
    ('jeju', 'jeju-seogwipo', '서귀포시', 2, NULL::double precision, NULL::double precision)
)
INSERT INTO "v1_regions" ("id", "parent_id", "code", "name", "level", "center_lat", "center_lng", "is_active", "sort_order", "created_at", "updated_at")
SELECT 'region-' || child.code, parent.id, child.code, child.name, 2, child.center_lat, child.center_lng, true, child.sort_order, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM child_rows child
JOIN "v1_regions" parent ON parent."code" = child.parent_code
ON CONFLICT ("code") DO UPDATE SET
  "parent_id" = EXCLUDED."parent_id",
  "name" = EXCLUDED."name",
  "level" = 2,
  "center_lat" = COALESCE(EXCLUDED."center_lat", "v1_regions"."center_lat"),
  "center_lng" = COALESCE(EXCLUDED."center_lng", "v1_regions"."center_lng"),
  "is_active" = true,
  "sort_order" = EXCLUDED."sort_order",
  "updated_at" = CURRENT_TIMESTAMP;
