ALTER TABLE "v1_tournaments"
ADD COLUMN IF NOT EXISTS "promo_home_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "promo_home_title" TEXT,
ADD COLUMN IF NOT EXISTS "promo_home_subtitle" TEXT,
ADD COLUMN IF NOT EXISTS "promo_home_image_url" TEXT,
ADD COLUMN IF NOT EXISTS "promo_home_badge_text" TEXT,
ADD COLUMN IF NOT EXISTS "promo_home_date_text" TEXT,
ADD COLUMN IF NOT EXISTS "promo_home_teams_text" TEXT,
ADD COLUMN IF NOT EXISTS "promo_home_location_text" TEXT,
ADD COLUMN IF NOT EXISTS "promo_home_prize_text" TEXT,
ADD COLUMN IF NOT EXISTS "promo_home_priority" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "promo_list_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "promo_list_title" TEXT,
ADD COLUMN IF NOT EXISTS "promo_list_subtitle" TEXT,
ADD COLUMN IF NOT EXISTS "promo_list_image_url" TEXT,
ADD COLUMN IF NOT EXISTS "promo_list_badge_text" TEXT,
ADD COLUMN IF NOT EXISTS "promo_list_date_text" TEXT,
ADD COLUMN IF NOT EXISTS "promo_list_teams_text" TEXT,
ADD COLUMN IF NOT EXISTS "promo_list_location_text" TEXT,
ADD COLUMN IF NOT EXISTS "promo_list_prize_text" TEXT,
ADD COLUMN IF NOT EXISTS "promo_list_priority" INTEGER NOT NULL DEFAULT 0;
