export const v1Keys = {
  all: ['v1'] as const,
  authMe: () => [...v1Keys.all, 'auth', 'me'] as const,
  onboarding: () => [...v1Keys.all, 'onboarding'] as const,
  masterSports: () => [...v1Keys.all, 'master', 'sports'] as const,
  masterRegions: () => [...v1Keys.all, 'master', 'regions'] as const,
  home: (filters?: Record<string, unknown>) => [...v1Keys.all, 'home', filters ?? {}] as const,
  recentSearches: () => [...v1Keys.all, 'search', 'recent'] as const,
  notices: (filters?: Record<string, unknown>) => [...v1Keys.all, 'notices', filters ?? {}] as const,
  notice: (noticeId: string) => [...v1Keys.all, 'notices', noticeId] as const,
  matches: (filters?: Record<string, unknown>) => [...v1Keys.all, 'matches', filters ?? {}] as const,
  match: (matchId: string) => [...v1Keys.all, 'matches', matchId] as const,
  teams: (filters?: Record<string, unknown>) => [...v1Keys.all, 'teams', filters ?? {}] as const,
  team: (teamId: string) => [...v1Keys.all, 'teams', teamId] as const,
  teamMatches: (filters?: Record<string, unknown>) => [...v1Keys.all, 'team-matches', filters ?? {}] as const,
  teamMatch: (teamMatchId: string) => [...v1Keys.all, 'team-matches', teamMatchId] as const,
  reviews: (filters?: Record<string, unknown>) => [...v1Keys.all, 'reviews', filters ?? {}] as const,
  reviewSource: (sourceType: string, sourceId: string) => [...v1Keys.all, 'reviews', 'sources', sourceType, sourceId] as const,
  reviewsReceived: (filters?: Record<string, unknown>) => [...v1Keys.all, 'reviews', 'received', filters ?? {}] as const,
  chatRooms: () => [...v1Keys.all, 'chat', 'rooms'] as const,
  chatRoom: (roomId: string) => [...v1Keys.chatRooms(), roomId] as const,
  chatMessages: (roomId: string) => [...v1Keys.chatRoom(roomId), 'messages'] as const,
  notifications: (filters?: Record<string, unknown>) => [...v1Keys.all, 'notifications', filters ?? {}] as const,
  notificationPreferences: () => [...v1Keys.all, 'notification-preferences'] as const,
  profile: () => [...v1Keys.all, 'me', 'profile'] as const,
  settings: () => [...v1Keys.all, 'me', 'settings'] as const,
  adminOverview: () => [...v1Keys.all, 'admin', 'overview'] as const,
  adminActionLogs: () => [...v1Keys.all, 'admin', 'action-logs'] as const,
  adminMe: () => [...v1Keys.all, 'admin', 'me'] as const,
  adminUsers: (filters?: Record<string, unknown>) => [...v1Keys.all, 'admin', 'users', filters ?? {}] as const,
  adminUser: (id: string) => [...v1Keys.all, 'admin', 'users', id] as const,
  adminMatches: (filters?: Record<string, unknown>) => [...v1Keys.all, 'admin', 'matches', filters ?? {}] as const,
  adminMatch: (id: string) => [...v1Keys.all, 'admin', 'matches', id] as const,
  adminTeams: (filters?: Record<string, unknown>) => [...v1Keys.all, 'admin', 'teams', filters ?? {}] as const,
  adminTeam: (id: string) => [...v1Keys.all, 'admin', 'teams', id] as const,
  adminTeamMatches: (filters?: Record<string, unknown>) => [...v1Keys.all, 'admin', 'team-matches', filters ?? {}] as const,
  adminStatusChangeLogs: (filters?: Record<string, unknown>) => [...v1Keys.all, 'admin', 'status-change-logs', filters ?? {}] as const,
  adminAdmins: (filters?: Record<string, unknown>) => [...v1Keys.all, 'admin', 'admins', filters ?? {}] as const,
  tournaments: (filters?: Record<string, unknown>) => [...v1Keys.all, 'tournaments', filters ?? {}] as const,
  tournament: (id: string) => [...v1Keys.all, 'tournaments', id] as const,
  tournamentRegistration: (tournamentId: string, registrationId: string) =>
    [...v1Keys.all, 'tournaments', tournamentId, 'registrations', registrationId] as const,
  tournamentPlayers: (tournamentId: string, registrationId: string) =>
    [...v1Keys.all, 'tournaments', tournamentId, 'registrations', registrationId, 'players'] as const,
  adminTournaments: (filters?: Record<string, unknown>) => [...v1Keys.all, 'admin', 'tournaments', filters ?? {}] as const,
  adminTournament: (id: string) => [...v1Keys.all, 'admin', 'tournaments', id] as const,
  adminTournamentRegistrations: (tournamentId: string, filters?: Record<string, unknown>) =>
    [...v1Keys.all, 'admin', 'tournaments', tournamentId, 'registrations', filters ?? {}] as const,
  adminTournamentBracket: (tournamentId: string) =>
    [...v1Keys.all, 'admin', 'tournaments', tournamentId, 'bracket'] as const,
};
